### ISSUE TITLE
Sidebar in portrait

### ISSUE THREAD

**Issue by sebastianludwig** [lurado/LDOBarController#29]
Sometimes `LDOBarView-updateConstraints` is not called (at least on iPad Air 2 simulator, iOS 9) which results in the wrong bar staying visible. I guess implementing `LDOBarController-willRotateToInterfaceOrentation` and calling `LDOBarView-setNeedsUpdateConstraints` should do the trick.

**Comment by jlnr** [comment]
-1 for `willRotate...` and +1 for `
- viewWillTransitionToSize:withTransitionCoordinator:`

**Comment by sebastianludwig** [comment]
Only if this issue never happens on iOS 7.

**Comment by jlnr** [comment]
Good point, but I don't think `willRotate...` is called during multitasking size changes. Haven't had the time to look at the code, so I might be making up a problem here.
